language: "python"
python:
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get -qq update

install:
  - pip install codecov
  - pip install .

script:
  - tests/test.sh

after_success:
  - codecov

branches:
  only:
    - master
    - dev
