language: "python"
python:
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get -qq update

install:
  - pip install codecov
  - pip install coverage
  - pip install .

script:
  - tests/test.sh
  - coverage run tests/core_tests.py
  - coverage report

after_success:
  - codecov

branches:
  only:
    - master
    - dev
