language: "python"
python:
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get -qq update

install:
  - pip install codecov
  - pip install coverage
  - pip install .

script:
  - tests/test.sh
  - coverage run tests/core_tests.opy
  - coverage report

after_success:
  - codecov

matrix:
  include:
    env:
      - "NUMPY_VERSION=1.12"
      - "NUMPY_VERSION=1.13"
    env:
      - "SKLEARN_VERSION=0.18"
      - "SKLEARN_VERSION=0.19"
    env:
      - "SCIPY_VERSION=0.18"
      - "SCIPY_VERSION=0.19"
      - "SCIPY_VERSION=1.0"

branches:
  only:
    - master
    - dev
